spring:
  jpa:
    defer-datasource-initialization: true
    database: H2
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  sql.init.mode: always

h2:
  console.enabled: true

datasource:
  driver-class-name: org.h2.Driver
  url: jdbc:h2:mem:test